version: "3"
services:
  git_container:
    build:
      context: .
    volumes:
      - "${PWD}:/git"
      - type: bind
        source: "${HOME}/.gitconfig:/.gitconfig"
        target: /.gitconfig
        read_only: true
      - type: bind
        source: "${HOME}/.ssh"
        target: /.ssh
        read_only: true
    tty: true
    stdin_open: true
